### ISSUE TITLE
讲了这么多还是不懂ipv6网段咋分的？谢谢

### ISSUE THREAD

**Issue by ygm521** [gnu4cn/skrzdwlgcs60d#2]

**Comment by gnu4cn** [comment]
IPv6由ISP提供前缀

**Comment by nonPointer** [comment]
IPv6 提供两种地址分配方式：
无状态分配：SLAAC，根据当前网络前缀和网关地址自动配置 IPv6 地址；
有状态分配：DHCPv6，由 DHCPv6 服务器统一分配客户端 IPv6 地址和前缀。
