### ISSUE TITLE
求个pdf版本,方便在移动设备上阅读

### ISSUE THREAD

**Issue by songyang8964** [gnu4cn/skrzdwlgcs60d#8]
epub也可以,之前有pdf的,更新后没了

**Comment by LennySCSZ** [comment]
我看看现在构建出来的是怎样的。

**Comment by gnu4cn** [comment]
看看能不能下载：[CCNA60D.Chinese.CCNA.60.days.epub](https://github.com/gnu4cn/ccna60d/releases/download/v0.0.2/CCNA60D.zh-CN.v0.0.2.epub)，不然就要上传到其他地方了。
